### ISSUE TITLE
psst, your chat logs are showing!

### ISSUE THREAD

**Issue by aamaliaa** [jescalan/config#1]
might want to remove these...!!

https://github.com/jenius/config/tree/master/adium/Adium%202.0/Users/Default/Logs/GTalk.jeff.escalante%40carrotcreative.com

**Comment by jescalan** [comment]
Wow, great call. I thought something silly like this might leak through. Thanks for the heads up!

**Comment by jescalan** [comment]
This is the one time I like the fact that you can go back and edit history with git. Resolved, and thanks again for the heads up : )

**Comment by aamaliaa** [comment]
no problem! thanks for posting this, i'm excited to check out sketch and pow! :)
